default_stages: [commit]
default_language_version:
  python: python3.10.9
repos:  
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      args: [
        --max-line-length=79
      ]
      ignore: W503
      exclude: ^(venv/|docs/)
      types: ['python']
      max-complexity: 10